dist: bionic
install: true
language: cpp
compiler: g++
script:
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - cd googletest
  - cmake .
  - cmake -DCMAKE_CXX_COMPILER="c++" -DCMAKE_CXX_FLAGS="-std=c++11" .
  - make clean
  - make all
  - cd ..
  - cd ..
  - make GOOGLETEST=./googletest/googletest
  - make
  - make test
